Add authorization domain validation
EdgarSedov/Steam pull request #1
Opened 2022-03-05 10:34 UTC by EdgarSedov

2022-03-05 11:55 UTC, Taalaybek requested changes

2022-03-05 11:55 UTC, Taalaybek commented on Provider.php
>          $realm = $this->getConfig('realm', $this->request->server('HTTP_HOST'));
blank space maybe?

2022-03-05 11:55 UTC, Taalaybek commented on Provider.php
> +    protected function validateUrl(string $url): bool
Let's change the name of the method to a more suitable one according to what it duz? 
something like this `checkInitialServiceUrl` or `verifyInitialServiceUrl`
but u can skip it

2022-03-05 12:04 UTC, eg00 commented on Provider.php
> +        if ($this->validateUrl($this->redirectUrl)) {
Может лучше здесь !$this->validateUrl($this->redirectUrl), а внутри метода  return in_array($urlParse, $allowedHosts);
Логичнее?

2022-03-05 12:04 UTC, eg00 commented on Provider.php
> +    protected function validateUrl(string $url): bool
ValidateHost?

2022-03-05 12:06 UTC, Taalaybek commented on Provider.php
> +    protected function validateUrl(string $url): bool
aw, it is nice

2022-03-09 09:37 UTC, Taalaybek approved these changes
Looks good

2022-03-09 12:49 UTC, EdgarSedov commented on Provider.php
> +
А почему это в функции buildUrl?)

2022-03-09 12:51 UTC, EdgarSedov commented
> Looks good

@Taalaybek резолвни треды свои :)

2022-03-09 13:23 UTC, Taalaybek commented
@EdgarSedov 
Already )

2022-03-09 15:08 UTC, EdgarSedov commented
> Already )

@Taalaybek 

![image](https://user-images.githubusercontent.com/16332716/157469560-d66cd0ec-f261-4d6c-b733-27b56ce8095b.png)

2022-03-09 15:12 UTC, Taalaybek approved these changes

2022-03-10 09:31 UTC, strd0x commented on Provider.php
> +
Чтоб заведомо не отправлять юзера на ненадежную ссылку

2022-03-10 10:22 UTC, EdgarSedov commented on Provider.php
> +
Пакет сам урл формирует на основе конфига - мы не доверяем самим себе или туплю?

2022-03-10 10:24 UTC, strd0x commented on Provider.php
> +
Думаю, стоит сделать игнор настройки, если allowed_hosts не существует и убрать ее отсюда

2022-03-10 10:26 UTC, Taalaybek approved these changes

2022-03-10 10:27 UTC, Taalaybek approved these changes

2022-03-10 10:28 UTC, Taalaybek approved these changes

2022-03-11 11:32 UTC, merged